
import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
import java.sql.*;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author architgarg
 */
public class applydl extends javax.swing.JFrame {

    String snm,sid;
    /**
     * Creates new form applydl
     */
    public applydl(String s1,String s2) {
        initComponents();
        snm=s1;
        sid=s2;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        ccat = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        teve = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cfd = new javax.swing.JComboBox<>();
        cfm = new javax.swing.JComboBox<>();
        cfy = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        ctd = new javax.swing.JComboBox<>();
        ctm = new javax.swing.JComboBox<>();
        cty = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        rf = new javax.swing.JRadioButton();
        rh = new javax.swing.JRadioButton();
        bapl = new javax.swing.JButton();
        bb = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1425, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("CATEGORY");
        jLabel2.setMaximumSize(new java.awt.Dimension(100, 50));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 100, -1, -1));

        ccat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Club EBuzz", "CSE Deptt Level", "ECE Deptt Level", "ME Deptt Level", "MUN Club", "SAP" }));
        ccat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ccatActionPerformed(evt);
            }
        });
        getContentPane().add(ccat, new org.netbeans.lib.awtextra.AbsoluteConstraints(605, 90, 170, -1));

        jLabel1.setText("EVENT");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 159, -1, -1));
        getContentPane().add(teve, new org.netbeans.lib.awtextra.AbsoluteConstraints(605, 154, 160, -1));

        jLabel3.setText("FROM DATE");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 215, -1, -1));

        cfd.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        getContentPane().add(cfd, new org.netbeans.lib.awtextra.AbsoluteConstraints(605, 211, 45, -1));

        cfm.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));
        cfm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cfmActionPerformed(evt);
            }
        });
        getContentPane().add(cfm, new org.netbeans.lib.awtextra.AbsoluteConstraints(678, 211, -1, -1));

        cfy.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2018" }));
        getContentPane().add(cfy, new org.netbeans.lib.awtextra.AbsoluteConstraints(818, 211, -1, -1));

        jLabel4.setText("TO DATE");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 278, -1, -1));

        ctd.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        getContentPane().add(ctd, new org.netbeans.lib.awtextra.AbsoluteConstraints(605, 274, 45, -1));

        ctm.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));
        getContentPane().add(ctm, new org.netbeans.lib.awtextra.AbsoluteConstraints(678, 274, -1, -1));

        cty.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2018" }));
        getContentPane().add(cty, new org.netbeans.lib.awtextra.AbsoluteConstraints(818, 274, -1, -1));

        jLabel5.setText(":");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 94, -1, -1));

        jLabel6.setText(":");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 159, 12, -1));

        jLabel7.setText(":");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 215, 12, -1));

        jLabel8.setText(":");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 278, 12, -1));

        jLabel9.setText("TIME SLOT");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 349, -1, -1));

        jLabel10.setText(":");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 349, 12, -1));

        rf.setText("Full Day");
        rf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rfActionPerformed(evt);
            }
        });
        getContentPane().add(rf, new org.netbeans.lib.awtextra.AbsoluteConstraints(605, 349, -1, -1));

        rh.setText("Half Day");
        getContentPane().add(rh, new org.netbeans.lib.awtextra.AbsoluteConstraints(743, 349, -1, -1));

        bapl.setText("Apply Leave");
        bapl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                baplActionPerformed(evt);
            }
        });
        getContentPane().add(bapl, new org.netbeans.lib.awtextra.AbsoluteConstraints(506, 400, 143, 49));

        bb.setText("<");
        bb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bbActionPerformed(evt);
            }
        });
        getContentPane().add(bb, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 87, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ccatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ccatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ccatActionPerformed

    private void rfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rfActionPerformed

    private void baplActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_baplActionPerformed
        // TODO add your handling code here:
        String fd,fm,fy,td,tm,ty,fdt,tdt,ts="";
             fd=String.valueOf(cfd.getSelectedItem());
             fm=String.valueOf(cfm.getSelectedItem());
             fy=String.valueOf(cfy.getSelectedItem());
             td=String.valueOf(ctd.getSelectedItem());
             tm=String.valueOf(ctm.getSelectedItem());
             ty=String.valueOf(cty.getSelectedItem());
             fdt=fd+"-"+fm+"-"+fy;
             if(rf.isSelected())
             {
                 ts="Full Day";
             }
             if(rh.isSelected())
             {
                 ts="Half Day";
             }
             tdt=td+"-"+tm+"-"+ty;
                  try{
        Class.forName("com.mysql.jdbc.Driver");
        Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/ChalkPad","root","mysql");
        PreparedStatement ps=con.prepareStatement("insert into dl values ('"+ccat.getSelectedItem()+"','"+teve.getText()+"','"+fdt+"','"+tdt+"','"+ts+"')");
        ps.executeUpdate();
        JOptionPane.showMessageDialog(this,"DL Applied Successfully");
        teve.setText("");
            }
            catch(Exception e1){
                System.out.println(e1);
            }
    }//GEN-LAST:event_baplActionPerformed

    private void cfmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cfmActionPerformed
        // TODO add your handling code here:
             
    }//GEN-LAST:event_cfmActionPerformed

    private void bbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bbActionPerformed
        
            this.dispose();
            dashstud d=new dashstud(snm,sid);
        
    }//GEN-LAST:event_bbActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(applydl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(applydl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(applydl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(applydl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               new applydl("","").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bapl;
    private javax.swing.JButton bb;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.JComboBox<String> ccat;
    private javax.swing.JComboBox<String> cfd;
    private javax.swing.JComboBox<String> cfm;
    private javax.swing.JComboBox<String> cfy;
    private javax.swing.JComboBox<String> ctd;
    private javax.swing.JComboBox<String> ctm;
    private javax.swing.JComboBox<String> cty;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton rf;
    private javax.swing.JRadioButton rh;
    private javax.swing.JTextField teve;
    // End of variables declaration//GEN-END:variables
}
